server:
  PORT: REPLACEYOURPORT

database:
  type: mysql
  host: REPLACEYOURHOST
  port: REPLACEYOURPORT
  username: REPLACEYOURUSERNAME
  password: REPLACEYOURPASSWORD
  database: REPLACEYOURDATABASE
  synchronize: true
  retryDelay: 500
  retryAttempts: 10
  autoLoadEntities: true
